trigger:
  - main

pool:
  vmImage: ubuntu-22.04

steps:

  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis configuration'
    inputs:
      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
      organization: '$(SONARCLOUD_ORG)'
      scannerMode: Other
      extraProperties: |
        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
        sonar.sources='./test'
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'