name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
          unzip sonar-scanner-cli-4.2.0.1873-linux.zip
          sudo mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
          export PATH=$PATH:/opt/sonar-scanner/bin

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }} \
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=./test

      - name: Fetch all branches
        run: git fetch --all
