name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }} \
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=./test
      - name: Fetch all branches
        run: git fetch --all
